# Generated by Django 5.1 on 2024-08-14 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Дата бронирования')),
                ('visit_time', models.TimeField(choices=[(0, '19:00'), (1, '19:30'), (2, '20:00'), (3, '20:30'), (4, '21:00'), (5, '21:30'), (6, '22:00')], verbose_name='Время бронирования')),
                ('number_of_guests', models.PositiveIntegerField(default=1, verbose_name='Количество гостей')),
                ('special_request', models.TextField(blank=True, null=True, verbose_name='Особые пожелания')),
                ('booking_status', models.CharField(choices=[('Сonfirmed', 'Подтверждено'), ('Rejected', 'Отклонено'), ('Awaiting confirmation', 'Ожидает подтверждения')], max_length=50, verbose_name='Статус бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
