# Generated by Django 5.1 on 2024-08-18 12:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_owner_client_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата бронирования'),
        ),
    ]
