# Generated by Django 5.1 on 2024-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='visit_time',
            field=models.TimeField(blank=True, choices=[('0', '19:00'), ('1', '19:30'), ('2', '20:00'), ('3', '20:30'), ('4', '21:00'), ('5', '21:30'), ('6', '22:00')], null=True, verbose_name='Время бронирования'),
        ),
    ]
