# Generated by Django 5.1 on 2024-08-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_booking_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='visit_time',
            field=models.CharField(blank=True, choices=[('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00')], null=True, verbose_name='Время бронирования'),
        ),
    ]
